"""
Code analysis patterns for different programming languages.

Adapted from CodeWiki (MIT License).
"""

from typing import List, Dict, Optional

DEFAULT_IGNORE_PATTERNS = {
    ".github",
    ".vscode",
    ".git",
    ".gitignore",
    ".gitmodules",
    "examples",
    # Python
    "*.pyc",
    "*.pyo",
    "*.pyd",
    "__pycache__",
    ".pytest_cache",
    ".coverage",
    ".tox",
    ".nox",
    ".mypy_cache",
    ".ruff_cache",
    ".hypothesis",
    "poetry.lock",
    "Pipfile.lock",
    # JavaScript
    "package-lock.json",
    "yarn.lock",
    ".npm",
    ".yarn",
    ".pnpm-store",
    "bun.lock",
    "bun.lockb",
    "node_modules",
    # Java
    "*.class",
    "*.jar",
    "*.war",
    "*.ear",
    "*.nar",
    ".gradle/",
    ".settings/",
    ".classpath",
    "gradle-app.setting",
    "*.gradle",
    ".project",
    # C/C++
    "*.o",
    "*.obj",
    "*.dll",
    "*.dylib",
    "*.exe",
    "*.lib",
    "*.out",
    "*.a",
    "*.pdb",
    # .NET/C#
    "*.suo",
    "*.user",
    "*.userosscache",
    "*.sln.docstates",
    "*.nupkg",
    "bin/",
    # Version control
    ".svn",
    ".hg",
    ".gitattributes",
    # Images and media
    "*.svg",
    "*.png",
    "*.jpg",
    "*.jpeg",
    "*.gif",
    "*.ico",
    "*.pdf",
    "*.mov",
    "*.mp4",
    "*.mp3",
    "*.wav",
    # Virtual environments
    "venv",
    ".venv",
    "env",
    ".env",
    "virtualenv",
    # IDEs and editors
    ".idea",
    ".vs",
    "*.swo",
    "*.swn",
    "*.sublime-*",
    # Temporary and cache files
    "*.log",
    "*.bak",
    "*.swp",
    "*.tmp",
    "*.temp",
    ".cache",
    ".sass-cache",
    ".DS_Store",
    "Thumbs.db",
    "desktop.ini",
    # Build directories and artifacts
    "*.egg-info",
    "*.egg",
    "*.whl",
    "*.so",
    "dist",
    "build",
    "target",
    # Documentation
    ".docusaurus",
    # Other
    "*.min.js",
    "*.min.css",
    "*.map",
    ".terraform",
    "*.tfstate*",
    "*.ini",
    "tests",
    "test",
    "Tests",
    "Test",
    "Examples",
}

DEFAULT_INCLUDE_PATTERNS = [
    "*.py",
    "*.js",
    "*.ts",
    "*.jsx",
    "*.tsx",
    "*.java",
    "*.cpp",
    "*.c",
    "*.h",
    "*.cs",
    "*.go",
    "*.rs",
    "*.php",
    "*.rb",
    "*.swift",
    "*.kt",
    "*.kts",
    "*.scala",
    "*.clj",
    "*.hs",
    "*.ml",
    "*.html",
    "*.css",
    "*.scss",
    "*.sass",
    "*.json",
    "*.yaml",
    "*.yml",
    "*.xml",
    "*.md",
    "*.txt",
    "*.toml",
    "*.cfg",
]

CODE_EXTENSIONS = {
    ".py": "python",
    ".js": "javascript",
    ".ts": "typescript",
    ".jsx": "javascript",
    ".tsx": "typescript",
    ".java": "java",
    ".cpp": "cpp",
    ".cc": "cpp",
    ".cxx": "cpp",
    ".c++": "cpp",
    ".c": "c",
    ".h": "c",
    ".hpp": "cpp",
    ".hxx": "cpp",
    ".h++": "cpp",
    ".rs": "rust",
    ".go": "go",
    ".php": "php",
    ".rb": "ruby",
    ".swift": "swift",
    ".kt": "kotlin",
    ".scala": "scala",
    ".cs": "csharp",
}
